#!/bin/sh
# Check that each vX.XX dir has a js/cache and css/cache dir existing, 
# and that owner/group is apache, and permissions are OK
#
# Exits with code 0 if everything is OK
# Exits with code 1 if something failed
#

RESULT=0
for dir in `find /data/vhosts/vyew.com/httpdocs -maxdepth 1 -type d  | egrep '\/v[4-9][0-9]?\.[0-9]+'`;do
	tmp=`ls -ld $dir/js/cache|grep 'apache apache'`
	if [ $? != 0 ] || [ ! -d "$dir/js/cache" ];then
		echo "MISSING OR WRONG PERMISSIONS: $dir/js/cache"
		RESULT=1
	fi
	tmp=`ls -ld $dir/css/cache|grep 'apache apache'`
	if [ $? != 0 ] || [ ! -d "$dir/css/cache" ];then
		echo "MISSING OR WRONG PERMISSIONS: $dir/css/cache"
		RESULT=1
	fi
done

[ $RESULT == 0 ] && echo "OK"
exit $RESULT



